services:
  # Servicio de PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: qwerty
      PMA_ARBITRARY: 1
  
  # Servicio de MySQL
  mysql-db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./dbfiles:/docker-entrypoint-initdb.d 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BD_Sistema_BiBlioteca
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # Servicio Front
  Sistema-BiBlioteca-Front:
    build:
      context: ./Sistema-BiBlioteca-Front
      dockerfile: Dockerfile
    container_name: Sistema-BiBlioteca-Front
    ports:
      - 80:80
  
  # Servicio del Backend
  Sistema-BiBlioteca-Back:
    build:
      context: ./Sistema-BiBlioteca-Back
      dockerfile: Dockerfile
    container_name: Sistema-BiBlioteca-Back
    ports:
      - "8080:3500"
    depends_on:
      - mysql-db
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.20'
          memory: 100M

